# Generated by Django 3.2.14 on 2022-07-27 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongMethodMaster',
            fields=[
                ('method_id', models.AutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('param_count', models.PositiveIntegerField(default=0)),
                ('return_type', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('review_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'long_method_master',
            },
        ),
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'project_master',
            },
        ),
        migrations.CreateModel(
            name='MethodWaitMaster',
            fields=[
                ('method_id', models.AutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('param_count', models.PositiveIntegerField(default=0)),
                ('return_type', models.CharField(max_length=100)),
                ('project_id', models.PositiveIntegerField(default=0)),
                ('path', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'method_wait_master',
                'unique_together': {('method_id', 'project_id')},
            },
        ),
    ]
