# Generated by Django 4.0.6 on 2022-08-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0002_projectmaster_class_count_projectmaster_method_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='longmethodmaster',
            name='content',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='methodwaitmaster',
            name='content',
            field=models.CharField(default='', max_length=100),
        ),
    ]
