# Generated by Django 4.0.6 on 2022-08-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0003_longmethodmaster_content_methodwaitmaster_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longmethodmaster',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='methodwaitmaster',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
