# Generated by Django 4.0.6 on 2022-08-08 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0004_alter_longmethodmaster_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodQues',
            fields=[
                ('method_ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('ques_id', models.PositiveIntegerField(default=0)),
                ('method_id', models.PositiveIntegerField(default=0)),
                ('answer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'method_ques',
            },
        ),
        migrations.CreateModel(
            name='NegMethodMaster',
            fields=[
                ('method_id', models.AutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('param_count', models.PositiveIntegerField(default=0)),
                ('return_type', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('review_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'neg_method_master',
            },
        ),
        migrations.CreateModel(
            name='QuesMaster',
            fields=[
                ('ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('ques', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ques_master',
            },
        ),
        migrations.AddField(
            model_name='longmethodmaster',
            name='ex_pos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='longmethodmaster',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
