# Generated by Django 4.0.6 on 2022-08-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0005_methodques_negmethodmaster_quesmaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodwaitmaster',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
