# Generated by Django 4.0.6 on 2022-08-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0007_posmethodmaster_delete_longmethodmaster_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posmethodmaster',
            table='pos_method_master',
        ),
    ]
