# Generated by Django 4.0.6 on 2022-08-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0008_alter_posmethodmaster_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PosMethodMaster',
        ),
    ]
