# Generated by Django 4.0.6 on 2022-08-08 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0009_delete_posmethodmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosMethodMaster',
            fields=[
                ('method_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('review_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.PositiveIntegerField(default=0)),
                ('ex_pos', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'pos_method_master',
            },
        ),
    ]
