# Generated by Django 4.0.6 on 2022-08-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0012_posmethodmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmaster',
            name='detail',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
