# Generated by Django 4.0.6 on 2022-08-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0013_alter_quesmaster_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='negmethodmaster',
            name='class_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negmethodmaster',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='negmethodmaster',
            name='method_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negmethodmaster',
            name='param_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='negmethodmaster',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negmethodmaster',
            name='project_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='negmethodmaster',
            name='return_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posmethodmaster',
            name='class_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posmethodmaster',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='posmethodmaster',
            name='method_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posmethodmaster',
            name='param_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posmethodmaster',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posmethodmaster',
            name='project_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posmethodmaster',
            name='return_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
