# Generated by Django 4.0.6 on 2022-08-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0014_negmethodmaster_class_name_negmethodmaster_content_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='methodques',
            unique_together={('ques_id', 'method_id')},
        ),
    ]
