# Generated by Django 4.0.6 on 2022-11-11 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0015_alter_methodques_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCProjectMaster',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('class_count', models.PositiveIntegerField(default=0)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'lc_project_master',
            },
        ),
    ]
