# Generated by Django 4.0.6 on 2022-11-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0017_lcnegclass_lcposclass_lcprojectmaster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcnegclass',
            name='project_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lcposclass',
            name='project_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
